import Head from "next/head";
import Header from "./components/Header";
import Image from "next/image";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1 className="text-3xl font-bold">Homepage</h1>
        </div>
      </main>
    </div>
  );
}
